# Generated by Django 4.2.6 on 2023-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interiors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='surname',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.CharField(default='', max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='first_name',
            field=models.CharField(default='', max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='last_name',
            field=models.CharField(default='', max_length=254, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='password',
            field=models.CharField(default='', max_length=254, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='username',
            field=models.CharField(default='', max_length=254, unique=True, verbose_name='Логин'),
        ),
    ]
